---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-b-echoserver
  namespace: default
  annotations:
    flux.weave.works/automated: 'true'
spec:
  template:
    spec:
      containers:
      - name: my-container
        image: nbadger/echoserver:dev-test-1
