version: 1
generators: 
  - command: kustomize build .
updaters:
  # use https://github.com/squaremo/kubeyaml on flux-patch.yaml
  - containerImage:
      command: >-
        echo 'n' | cp -i ./patches/template-patch-flux.yaml ./patches/patch-flux-$FLUX_WL_NAME.yaml &&
        sed 's/$FLUX_CONTAINER/'"$FLUX_CONTAINER"'/' -i ./patches/patch-flux-$FLUX_WL_NAME.yaml &&
        sed 's/$FLUX_IMG/'"$FLUX_IMG"'/' -i ./patches/patch-flux-$FLUX_WL_NAME.yaml &&
        sed 's/$FLUX_TAG/'"$FLUX_TAG"'/' -i ./patches/patch-flux-$FLUX_WL_NAME.yaml &&
        sed 's/$FLUX_WL_NAME/'"$FLUX_WL_NAME"'/' -i ./patches/patch-flux-$FLUX_WL_NAME.yaml &&
        sed 's/$FLUX_WL_NS/'"$FLUX_WL_NS"'/' -i ./patches/patch-flux-$FLUX_WL_NAME.yaml &&
        kustomize edit add patch patches/*.yaml
