apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: team-a-echoserver
  name: team-a-echoserver
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team-a-echoserver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: team-a-echoserver
    spec:
      containers:
      - imagePullPolicy: IfNotPresent
        name: my-container
        image: my-image
