apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flux
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: flux
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        prometheus.io.port: "3031"
      labels:
        name: flux
    spec:
      containers:
      - args:
        - --memcached-service=
        - --ssh-keygen-dir=/var/fluxd/keygen
        - --git-url=git@gitlab.com:nabadger/flux-ci-promotion.git
        - --git-branch=master
        - --git-path=kustomize/prod/
        - --listen-metrics=:3031
        image: docker.io/2opremio/flux:generators-releasers-8baf8bd0
        imagePullPolicy: IfNotPresent
        name: flux
        ports:
        - containerPort: 3030
          protocol: TCP
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
        volumeMounts:
        - name: git-key
          mountPath: /etc/fluxd/ssh # to match location given in image's /etc/ssh/config
          readOnly: true # this will be the case perforce in K8s >=1.10                
        - mountPath: /var/fluxd/keygen
          name: git-keygen
      dnsPolicy: ClusterFirst
      serviceAccount: flux
      serviceAccountName: flux
      terminationGracePeriodSeconds: 30
      volumes:
      - name: git-key
        secret:
          secretName: flux-git-deploy
          defaultMode: 0400 # when mounted read-only, we won't be able to chmod              
      - emptyDir:
          medium: Memory
        name: git-keygen
